version: '3.7'
services:
  grafana_dev:
    restart: &grafana-restart always
    image: perfsonar/grafana-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      &grafana-env
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource,esnet-matrix-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_PROVISIONING=/usr/lib/perfsonar/grafana/provisioning
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      &grafana-ports
       - 3000:3000